#2 Подключение WebPack
PomanoB/Soliferrum pull request #15
Opened 2018-03-10 16:53 UTC by PomanoB

2018-03-10 23:51 UTC, RSamokhin requested changes

2018-03-10 23:51 UTC, RSamokhin commented on dist/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
че за говно, убрать наверно

2018-03-10 23:51 UTC, RSamokhin commented on dist/index.html
> +<!doctype html>
тоже, вроде надо заигнорить

2018-03-11 14:11 UTC, PomanoB commented on dist/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
Убрал

2018-03-11 14:12 UTC, PomanoB commented on dist/index.html
> +<!doctype html>
Заигнорил всю папку

2018-03-11 15:07 UTC, RSamokhin approved these changes

2018-03-11 15:07 UTC, merged